language: node_js
node_js:
- 10.15.3

addons:
  homebrew:
    packages:
    - sqlite
    - sqlcipher

jobs:
  include:
    - os: osx
      env:
        - INSTANCE=sz
    - os: windows
      cache: false
      env:
        - INSTANCE=sz

    - os: osx
      env:
        - INSTANCE=bf
    - os: windows
      cache: false
      env:
        - INSTANCE=bf

before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine

cache:
  yarn: true
  directories:
    - node_modules
    - $(npm config get prefix)/lib/node_modules
    - flow-typed
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

before_install:
  - if [ "$TRAVIS_OS_NAME" == "windows" ]; then powershell -command 'Set-MpPreference -DisableRealtimeMonitoring $true'; fi
  - if [ "$TRAVIS_OS_NAME" == "windows" ]; then powershell -command 'Set-MpPreference -DisableArchiveScanning $true'; fi
  - if [ "$TRAVIS_OS_NAME" == "windows" ]; then powershell -command 'Set-MpPreference -DisableBehaviorMonitoring $true'; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then choco install sqlite --params "/NoTools"; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then yarn config delete proxy; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then npm config rm proxy; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then npm config rm https-proxy; fi

install:
  - yarn install --ignore-engines  --network-timeout 1000000

script:
  - yarn postinstall
  # - yarn lint
  # # # HACK: Temporarily ignore `yarn flow` on windows
  # - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then yarn flow; fi
  # - yarn build-e2e
  # - yarn test-e2e

after_success:
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then yarn package-ci; fi
  - if [[ "$TRAVIS_BRANCH" == "release-improvement" ]]; then node release.js; fi

notifications:
  email: false
