import { fetchEntity, fetchEntitySingular } from './fetch';

const FETCH_ELECTRONIC_PHARMACY_STOCK_RECORDS =
  'FETCH_ELECTRONIC_PHARMACY_STOCK_RECORDS';
const FETCH_ELECTRONIC_PHARMACY_STOCK_RECORD =
  'FETCH_ELECTRONIC_PHARMACY_STOCK_RECORD';
const FETCHED_ELECTRONIC_PHARMACY_STOCK_RECORDS =
  'FETCHED_ELECTRONIC_PHARMACY_STOCK_RECORDS';
const FETCHED_ELECTRONIC_PHARMACY_STOCK_RECORD =
  'FETCHED_ELECTRONIC_PHARMACY_STOCK_RECORD';

export const fetchElectronicPharmacyStockRecords = fetchEntity(
  'ElectronicPharmacyStockRecord'
);
export const fetchElectronicPharmacyStockRecord = fetchEntitySingular(
  'ElectronicPharmacyStockRecord'
);

export {
  FETCH_ELECTRONIC_PHARMACY_STOCK_RECORDS,
  FETCH_ELECTRONIC_PHARMACY_STOCK_RECORD,
  FETCHED_ELECTRONIC_PHARMACY_STOCK_RECORDS,
  FETCHED_ELECTRONIC_PHARMACY_STOCK_RECORD
};
