name: Build

on:
  - push

jobs:
  build-and-test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '10.15.3'
      - name: Install dependencies
        run: yarn install --ignore-engines  --network-timeout 1000000
      - name: Post-install
        run: yarn postinstall
      - name: Lint
        run: yarn lint
      - name: Flow
        run: yarn flow
      - name: Build End-to-End Tests
        run: yarn build-e2e
      - name: Run End-to-End Tests
        run: xvfb-run --server-args="-screen 0 1280x720x24" yarn test-e2e
  build-windows:
    runs-on: windows-2019
    needs: build-and-test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '10.15.3'
      - name: Install dependencies
        run: yarn install --ignore-engines  --network-timeout 1000000
      - name: Post-install
        run: yarn postinstall
      - name: Build
        run: yarn build
  build-macos:
    runs-on: macos-10.15
    needs: build-and-test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '10.15.3'
      - name: Install dependencies
        run: yarn install --ignore-engines  --network-timeout 1000000
      - name: Post-install
        run: yarn postinstall
      - name: Build
        run: yarn build
